//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/AA_Scripts/Biros/BiroInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @BiroInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @BiroInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""BiroInputActions"",
    ""maps"": [
        {
            ""name"": ""FlickGameplay"",
            ""id"": ""3954a0ac-f6f3-45fd-a3c5-4420868aeec2"",
            ""actions"": [
                {
                    ""name"": ""SelectAction"",
                    ""type"": ""Button"",
                    ""id"": ""4c0cee0d-9906-490e-b7a7-c1bdaf896b3c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseDelta"",
                    ""type"": ""Value"",
                    ""id"": ""0fadfc77-2db0-40e3-9b55-d4b36f039d38"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""7af7611c-64c3-4af9-85d3-2e28c747c7b9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""FlickChargeAction"",
                    ""type"": ""Button"",
                    ""id"": ""f8af6aa9-1bcb-46c7-a90d-b2ff7a5632ad"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpinMoveAction"",
                    ""type"": ""Button"",
                    ""id"": ""e34e7f40-4465-47b5-a267-3c80b17c7c98"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0e9c4bbb-adb7-42bb-b893-4d46b0498e1a"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""SelectAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d4d3be5c-e5b3-4e03-9f2f-86bf824106c3"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""MouseDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""65546ed1-5d56-4d6a-9cfc-0a3f0776b8ea"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5bde16b6-42e5-49fc-9c0c-31354aba953e"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""FlickChargeAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c6f8fd5a-a510-4e08-8ce5-66cc0c8f3b9a"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""SpinMoveAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Camera"",
            ""id"": ""46f76dad-e622-4f7c-a84d-62d52d629494"",
            ""actions"": [
                {
                    ""name"": ""OrbitModifier"",
                    ""type"": ""Button"",
                    ""id"": ""f2f92657-1993-4eba-b114-4854c9ca8da1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OrbitDelta"",
                    ""type"": ""Value"",
                    ""id"": ""7c6ca97f-d82d-48da-b857-2a935aedff00"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ZoomAction"",
                    ""type"": ""Value"",
                    ""id"": ""2a2e949d-2fe3-4cda-a3f2-03c5969a25d5"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ResetAction"",
                    ""type"": ""Button"",
                    ""id"": ""87952c09-8528-41a0-9536-8c0016c49ace"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ab70704e-cc2a-456f-ba18-10823e51df6b"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""OrbitModifier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""24107ce3-9881-4a2e-a778-096cc199034d"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""OrbitDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cf0ace32-edc5-4a98-9804-0f215548db33"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""ZoomAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ac8624a7-628d-4b79-adc8-af9a03c7fb51"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""ResetAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // FlickGameplay
        m_FlickGameplay = asset.FindActionMap("FlickGameplay", throwIfNotFound: true);
        m_FlickGameplay_SelectAction = m_FlickGameplay.FindAction("SelectAction", throwIfNotFound: true);
        m_FlickGameplay_MouseDelta = m_FlickGameplay.FindAction("MouseDelta", throwIfNotFound: true);
        m_FlickGameplay_MousePosition = m_FlickGameplay.FindAction("MousePosition", throwIfNotFound: true);
        m_FlickGameplay_FlickChargeAction = m_FlickGameplay.FindAction("FlickChargeAction", throwIfNotFound: true);
        m_FlickGameplay_SpinMoveAction = m_FlickGameplay.FindAction("SpinMoveAction", throwIfNotFound: true);
        // Camera
        m_Camera = asset.FindActionMap("Camera", throwIfNotFound: true);
        m_Camera_OrbitModifier = m_Camera.FindAction("OrbitModifier", throwIfNotFound: true);
        m_Camera_OrbitDelta = m_Camera.FindAction("OrbitDelta", throwIfNotFound: true);
        m_Camera_ZoomAction = m_Camera.FindAction("ZoomAction", throwIfNotFound: true);
        m_Camera_ResetAction = m_Camera.FindAction("ResetAction", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // FlickGameplay
    private readonly InputActionMap m_FlickGameplay;
    private List<IFlickGameplayActions> m_FlickGameplayActionsCallbackInterfaces = new List<IFlickGameplayActions>();
    private readonly InputAction m_FlickGameplay_SelectAction;
    private readonly InputAction m_FlickGameplay_MouseDelta;
    private readonly InputAction m_FlickGameplay_MousePosition;
    private readonly InputAction m_FlickGameplay_FlickChargeAction;
    private readonly InputAction m_FlickGameplay_SpinMoveAction;
    public struct FlickGameplayActions
    {
        private @BiroInputActions m_Wrapper;
        public FlickGameplayActions(@BiroInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @SelectAction => m_Wrapper.m_FlickGameplay_SelectAction;
        public InputAction @MouseDelta => m_Wrapper.m_FlickGameplay_MouseDelta;
        public InputAction @MousePosition => m_Wrapper.m_FlickGameplay_MousePosition;
        public InputAction @FlickChargeAction => m_Wrapper.m_FlickGameplay_FlickChargeAction;
        public InputAction @SpinMoveAction => m_Wrapper.m_FlickGameplay_SpinMoveAction;
        public InputActionMap Get() { return m_Wrapper.m_FlickGameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FlickGameplayActions set) { return set.Get(); }
        public void AddCallbacks(IFlickGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_FlickGameplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_FlickGameplayActionsCallbackInterfaces.Add(instance);
            @SelectAction.started += instance.OnSelectAction;
            @SelectAction.performed += instance.OnSelectAction;
            @SelectAction.canceled += instance.OnSelectAction;
            @MouseDelta.started += instance.OnMouseDelta;
            @MouseDelta.performed += instance.OnMouseDelta;
            @MouseDelta.canceled += instance.OnMouseDelta;
            @MousePosition.started += instance.OnMousePosition;
            @MousePosition.performed += instance.OnMousePosition;
            @MousePosition.canceled += instance.OnMousePosition;
            @FlickChargeAction.started += instance.OnFlickChargeAction;
            @FlickChargeAction.performed += instance.OnFlickChargeAction;
            @FlickChargeAction.canceled += instance.OnFlickChargeAction;
            @SpinMoveAction.started += instance.OnSpinMoveAction;
            @SpinMoveAction.performed += instance.OnSpinMoveAction;
            @SpinMoveAction.canceled += instance.OnSpinMoveAction;
        }

        private void UnregisterCallbacks(IFlickGameplayActions instance)
        {
            @SelectAction.started -= instance.OnSelectAction;
            @SelectAction.performed -= instance.OnSelectAction;
            @SelectAction.canceled -= instance.OnSelectAction;
            @MouseDelta.started -= instance.OnMouseDelta;
            @MouseDelta.performed -= instance.OnMouseDelta;
            @MouseDelta.canceled -= instance.OnMouseDelta;
            @MousePosition.started -= instance.OnMousePosition;
            @MousePosition.performed -= instance.OnMousePosition;
            @MousePosition.canceled -= instance.OnMousePosition;
            @FlickChargeAction.started -= instance.OnFlickChargeAction;
            @FlickChargeAction.performed -= instance.OnFlickChargeAction;
            @FlickChargeAction.canceled -= instance.OnFlickChargeAction;
            @SpinMoveAction.started -= instance.OnSpinMoveAction;
            @SpinMoveAction.performed -= instance.OnSpinMoveAction;
            @SpinMoveAction.canceled -= instance.OnSpinMoveAction;
        }

        public void RemoveCallbacks(IFlickGameplayActions instance)
        {
            if (m_Wrapper.m_FlickGameplayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IFlickGameplayActions instance)
        {
            foreach (var item in m_Wrapper.m_FlickGameplayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_FlickGameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public FlickGameplayActions @FlickGameplay => new FlickGameplayActions(this);

    // Camera
    private readonly InputActionMap m_Camera;
    private List<ICameraActions> m_CameraActionsCallbackInterfaces = new List<ICameraActions>();
    private readonly InputAction m_Camera_OrbitModifier;
    private readonly InputAction m_Camera_OrbitDelta;
    private readonly InputAction m_Camera_ZoomAction;
    private readonly InputAction m_Camera_ResetAction;
    public struct CameraActions
    {
        private @BiroInputActions m_Wrapper;
        public CameraActions(@BiroInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @OrbitModifier => m_Wrapper.m_Camera_OrbitModifier;
        public InputAction @OrbitDelta => m_Wrapper.m_Camera_OrbitDelta;
        public InputAction @ZoomAction => m_Wrapper.m_Camera_ZoomAction;
        public InputAction @ResetAction => m_Wrapper.m_Camera_ResetAction;
        public InputActionMap Get() { return m_Wrapper.m_Camera; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CameraActions set) { return set.Get(); }
        public void AddCallbacks(ICameraActions instance)
        {
            if (instance == null || m_Wrapper.m_CameraActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CameraActionsCallbackInterfaces.Add(instance);
            @OrbitModifier.started += instance.OnOrbitModifier;
            @OrbitModifier.performed += instance.OnOrbitModifier;
            @OrbitModifier.canceled += instance.OnOrbitModifier;
            @OrbitDelta.started += instance.OnOrbitDelta;
            @OrbitDelta.performed += instance.OnOrbitDelta;
            @OrbitDelta.canceled += instance.OnOrbitDelta;
            @ZoomAction.started += instance.OnZoomAction;
            @ZoomAction.performed += instance.OnZoomAction;
            @ZoomAction.canceled += instance.OnZoomAction;
            @ResetAction.started += instance.OnResetAction;
            @ResetAction.performed += instance.OnResetAction;
            @ResetAction.canceled += instance.OnResetAction;
        }

        private void UnregisterCallbacks(ICameraActions instance)
        {
            @OrbitModifier.started -= instance.OnOrbitModifier;
            @OrbitModifier.performed -= instance.OnOrbitModifier;
            @OrbitModifier.canceled -= instance.OnOrbitModifier;
            @OrbitDelta.started -= instance.OnOrbitDelta;
            @OrbitDelta.performed -= instance.OnOrbitDelta;
            @OrbitDelta.canceled -= instance.OnOrbitDelta;
            @ZoomAction.started -= instance.OnZoomAction;
            @ZoomAction.performed -= instance.OnZoomAction;
            @ZoomAction.canceled -= instance.OnZoomAction;
            @ResetAction.started -= instance.OnResetAction;
            @ResetAction.performed -= instance.OnResetAction;
            @ResetAction.canceled -= instance.OnResetAction;
        }

        public void RemoveCallbacks(ICameraActions instance)
        {
            if (m_Wrapper.m_CameraActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICameraActions instance)
        {
            foreach (var item in m_Wrapper.m_CameraActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CameraActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CameraActions @Camera => new CameraActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    public interface IFlickGameplayActions
    {
        void OnSelectAction(InputAction.CallbackContext context);
        void OnMouseDelta(InputAction.CallbackContext context);
        void OnMousePosition(InputAction.CallbackContext context);
        void OnFlickChargeAction(InputAction.CallbackContext context);
        void OnSpinMoveAction(InputAction.CallbackContext context);
    }
    public interface ICameraActions
    {
        void OnOrbitModifier(InputAction.CallbackContext context);
        void OnOrbitDelta(InputAction.CallbackContext context);
        void OnZoomAction(InputAction.CallbackContext context);
        void OnResetAction(InputAction.CallbackContext context);
    }
}
